In [1]:
import numpy as np

In [2]:
#Array manuplation

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[5, 5, 6, 7],
       [4, 3, 6, 9],
       [9, 4, 7, 1]], dtype=int32)

In [5]:
arr.reshape(6,2)

array([[5, 5],
       [6, 7],
       [4, 3],
       [6, 9],
       [9, 4],
       [7, 1]], dtype=int32)

In [6]:
arr.T

array([[5, 4, 9],
       [5, 3, 4],
       [6, 6, 7],
       [7, 9, 1]], dtype=int32)

In [7]:
arr.flatten()

array([5, 5, 6, 7, 4, 3, 6, 9, 9, 4, 7, 1], dtype=int32)

In [8]:
arr1 = np.array([1,2,3,4,5])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
arr2 = np.expand_dims(arr1,axis=0)

In [13]:
arr2.ndim

2

In [16]:
arr3 = np.squeeze(arr2)

In [17]:
arr3.ndim

1

In [18]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [19]:
np.repeat(arr,3)

array([5, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 4, 4, 4, 3, 3, 3, 6, 6, 6, 9,
       9, 9, 9, 9, 9, 4, 4, 4, 7, 7, 7, 1, 1, 1], dtype=int32)

In [20]:
arr

array([[5, 5, 6, 7],
       [4, 3, 6, 9],
       [9, 4, 7, 1]], dtype=int32)

In [23]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [24]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
#binary opreation

In [28]:
arr1 = np.random.randint(1,10,(3,4))

In [29]:
arr2 = np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[5, 3, 9, 4],
       [2, 4, 8, 4],
       [8, 6, 3, 2]], dtype=int32)

In [31]:
arr2

array([[6, 9, 3, 3],
       [6, 7, 6, 9],
       [4, 7, 6, 5]], dtype=int32)

In [32]:
arr1+arr2

array([[11, 12, 12,  7],
       [ 8, 11, 14, 13],
       [12, 13,  9,  7]], dtype=int32)

In [33]:
arr1-arr2

array([[-1, -6,  6,  1],
       [-4, -3,  2, -5],
       [ 4, -1, -3, -3]], dtype=int32)

In [34]:
arr1/arr2

array([[0.83333333, 0.33333333, 3.        , 1.33333333],
       [0.33333333, 0.57142857, 1.33333333, 0.44444444],
       [2.        , 0.85714286, 0.5       , 0.4       ]])

In [35]:
arr1*arr2

array([[30, 27, 27, 12],
       [12, 28, 48, 36],
       [32, 42, 18, 10]], dtype=int32)

In [37]:
arr1 ** arr2

array([[ 15625,  19683,    729,     64],
       [    64,  16384, 262144, 262144],
       [  4096, 279936,    729,     32]], dtype=int32)

In [38]:
arr1 & arr2

array([[4, 1, 1, 0],
       [2, 4, 0, 0],
       [0, 6, 2, 0]], dtype=int32)

In [39]:
~arr1

array([[ -6,  -4, -10,  -5],
       [ -3,  -5,  -9,  -5],
       [ -9,  -7,  -4,  -3]], dtype=int32)

In [40]:
arr1 | arr2

array([[ 7, 11, 11,  7],
       [ 6,  7, 14, 13],
       [12,  7,  7,  7]], dtype=int32)

In [41]:
arr1>arr2

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True, False, False, False]])

In [42]:
#String Function

In [43]:
arr = np.array(['Apurva','Aryan'])

In [44]:
np.char.upper(arr)

array(['APURVA', 'ARYAN'], dtype='<U6')

In [46]:
np.char.title(arr)

array(['Apurva', 'Aryan'], dtype='<U6')

In [47]:
np.char.capitalize(arr)

array(['Apurva', 'Aryan'], dtype='<U6')

In [50]:
#mathematical

In [51]:
arr1

array([[5, 3, 9, 4],
       [2, 4, 8, 4],
       [8, 6, 3, 2]], dtype=int32)

In [52]:
np.sin(arr1)

array([[-0.95892427,  0.14112001,  0.41211849, -0.7568025 ],
       [ 0.90929743, -0.7568025 ,  0.98935825, -0.7568025 ],
       [ 0.98935825, -0.2794155 ,  0.14112001,  0.90929743]])

In [53]:
np.cos(arr1)

array([[ 0.28366219, -0.9899925 , -0.91113026, -0.65364362],
       [-0.41614684, -0.65364362, -0.14550003, -0.65364362],
       [-0.14550003,  0.96017029, -0.9899925 , -0.41614684]])

In [54]:
np.tan(arr1)

array([[-3.38051501, -0.14254654, -0.45231566,  1.15782128],
       [-2.18503986,  1.15782128, -6.79971146,  1.15782128],
       [-6.79971146, -0.29100619, -0.14254654, -2.18503986]])

In [55]:
np.tanh(arr1)

array([[0.9999092 , 0.99505475, 0.99999997, 0.9993293 ],
       [0.96402758, 0.9993293 , 0.99999977, 0.9993293 ],
       [0.99999977, 0.99998771, 0.99505475, 0.96402758]])

In [56]:
np.log10(arr1)

array([[0.69897   , 0.47712125, 0.95424251, 0.60205999],
       [0.30103   , 0.60205999, 0.90308999, 0.60205999],
       [0.90308999, 0.77815125, 0.47712125, 0.30103   ]])

In [57]:
np.exp(arr1)

array([[1.48413159e+02, 2.00855369e+01, 8.10308393e+03, 5.45981500e+01],
       [7.38905610e+00, 5.45981500e+01, 2.98095799e+03, 5.45981500e+01],
       [2.98095799e+03, 4.03428793e+02, 2.00855369e+01, 7.38905610e+00]])

In [58]:
np.sqrt(arr1)

array([[2.23606798, 1.73205081, 3.        , 2.        ],
       [1.41421356, 2.        , 2.82842712, 2.        ],
       [2.82842712, 2.44948974, 1.73205081, 1.41421356]])

In [60]:
np.power(arr1,3)

array([[125,  27, 729,  64],
       [  8,  64, 512,  64],
       [512, 216,  27,   8]], dtype=int32)

In [61]:
np.mean(arr1)

np.float64(4.833333333333333)

In [62]:
np.median(arr1)

np.float64(4.0)

In [63]:
np.std(arr1)

np.float64(2.3033791601808753)

In [64]:
np.var(arr1)

np.float64(5.305555555555555)

In [65]:
np.min(arr1)

np.int32(2)

In [66]:
np.max(arr1)

np.int32(9)