In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4, 5])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [15]:
a = np.array(l)

In [16]:
c = a

In [17]:
c

array([1, 2, 3, 4, 5])

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
c[0]

np.int64(1)

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4,   5])

In [22]:
a

array([100,   2,   3,   4,   5])

In [23]:
d = np.copy(a)

In [24]:
d

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [26]:
d[1]= 200

In [27]:
d

array([100, 200,   3,   4,   5])

In [28]:
a

array([100,   2,   3,   4,   5])

In [31]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = (i * i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('234 235',sep=' ')

array([234., 235.])

In [38]:
#numpy Data Types

In [40]:
ar

array([1, 2, 3, 4, 5])

In [41]:
ar.ndim

1

In [42]:
ar.size

5

In [43]:
ar2 = np.array([l])

In [44]:
ar2.ndim

2

In [45]:
ar2.size

5

In [46]:
ar.shape

(5,)

In [48]:
ar2.shape

(1, 5)

In [49]:
ar.dtype

dtype('int64')

In [51]:
ar22 = np.array([(1.4,45,66),(23,55,66)])

In [52]:
ar22

array([[ 1.4, 45. , 66. ],
       [23. , 55. , 66. ]])

In [53]:
ar22.dtype

dtype('float64')

In [54]:
ar22.ndim

2

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
np.arange(1.1,5.1)

array([1.1, 2.1, 3.1, 4.1])

In [58]:
np.arange(1.1,5.1,0.1)

array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3,
       2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. ])

In [59]:
list(np.arange(1.1,5.1,0.1))

[np.float64(1.1),
 np.float64(1.2000000000000002),
 np.float64(1.3000000000000003),
 np.float64(1.4000000000000004),
 np.float64(1.5000000000000004),
 np.float64(1.6000000000000005),
 np.float64(1.7000000000000006),
 np.float64(1.8000000000000007),
 np.float64(1.9000000000000008),
 np.float64(2.000000000000001),
 np.float64(2.100000000000001),
 np.float64(2.200000000000001),
 np.float64(2.300000000000001),
 np.float64(2.4000000000000012),
 np.float64(2.5000000000000013),
 np.float64(2.6000000000000014),
 np.float64(2.7000000000000015),
 np.float64(2.8000000000000016),
 np.float64(2.9000000000000017),
 np.float64(3.0000000000000018),
 np.float64(3.100000000000002),
 np.float64(3.200000000000002),
 np.float64(3.300000000000002),
 np.float64(3.400000000000002),
 np.float64(3.500000000000002),
 np.float64(3.6000000000000023),
 np.float64(3.7000000000000024),
 np.float64(3.8000000000000025),
 np.float64(3.9000000000000026),
 np.float64(4.000000000000003),
 np.float64(4.100000000000003),
 np

In [60]:
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [61]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
on = np.ones((2,3,2))

In [70]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [71]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [72]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.62467093e-306]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [77]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [83]:
np.logspace(2,3,3)

array([ 100.        ,  316.22776602, 1000.        ])

In [86]:
arr = np.random.randn(3,4)

In [85]:
import pandas as pd

In [87]:
pd.DataFrame(arr)

0         1         2         3
0 -0.209350 -0.010991 -0.470321  0.626818
1  2.285953 -0.509396 -0.704344  1.397734
2  0.708302 -1.125162  1.698939 -0.165861

In [88]:
np.random.rand(3,4)

array([[0.6580475 , 0.44763715, 0.11734522, 0.7441151 ],
       [0.31230077, 0.93061126, 0.29472548, 0.86033492],
       [0.97333229, 0.57687752, 0.12154742, 0.82429381]])

In [90]:
np.random.randint(1,100,(3,4))

array([[ 1, 24, 90, 46],
       [91,  6, 51, 15],
       [ 9, 34, 47, 21]], dtype=int32)

In [91]:
arr

array([[-0.20935029, -0.0109914 , -0.47032122,  0.62681825],
       [ 2.28595274, -0.50939643, -0.70434375,  1.39773424],
       [ 0.70830173, -1.12516153,  1.69893869, -0.16586122]])

In [92]:
 arr = np.random.rand(3,4)

In [98]:
arr1 = arr.reshape(6,2)

In [103]:
arr1[1][1]

np.float64(0.8869655035289514)

In [105]:
arr = np.random.randint(1,100,(5,5))

In [106]:
arr >50

array([[ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False,  True],
       [ True, False,  True, False, False]])

In [107]:
arr[arr>50]

array([90, 73, 89, 68, 62, 53, 55, 57, 90], dtype=int32)

In [108]:
arr

array([[90, 73, 41, 28, 35],
       [ 9, 89, 68, 24, 30],
       [31, 62, 26, 26, 12],
       [ 4, 44, 53, 44, 55],
       [57, 18, 90,  7,  3]], dtype=int32)

In [109]:
arr[2:4,[1,2]]

array([[62, 26],
       [44, 53]], dtype=int32)

In [112]:
arr[0][0] = 5000

In [113]:
arr

array([[5000,   73,   41,   28,   35],
       [   9,   89,   68,   24,   30],
       [  31,   62,   26,   26,   12],
       [   4,   44,   53,   44,   55],
       [  57,   18,   90,    7,    3]], dtype=int32)

In [115]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))


In [116]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 2]], dtype=int32)

In [117]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [118]:
arr1+arr2

array([[2, 4, 3],
       [2, 4, 3],
       [2, 3, 3]], dtype=int32)

In [119]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0, -1],
       [ 0,  1,  1]], dtype=int32)

In [120]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 0.5],
       [1. , 2. , 2. ]])

In [121]:
arr1*arr2

array([[1, 4, 2],
       [1, 4, 2],
       [1, 2, 2]], dtype=int32)

In [122]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 2]], dtype=int32)

In [123]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [124]:
arr1@arr2

array([[4, 7, 7],
       [4, 7, 7],
       [5, 8, 8]], dtype=int32)

In [125]:
arr1/0

C:\Users\91736\AppData\Local\Temp\ipykernel_21680\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [126]:
arr1 **2

array([[1, 4, 1],
       [1, 4, 1],
       [1, 4, 4]], dtype=int32)

In [127]:
#numpy Broadcasting

In [128]:
arr = np.zeros((4,4))

In [129]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
row = np.array([1,2,3,4])

In [131]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [134]:
row.T

array([1, 2, 3, 4])

In [135]:
col = np.array([[1,2,3,4]])

In [136]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [138]:
arr+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [139]:
arr1 = np.random.randint(1,4,(3,4))

In [140]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.73205081, 1.41421356],
       [1.        , 1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.41421356]])

In [141]:
np.exp(arr1)

array([[ 2.71828183, 20.08553692, 20.08553692,  7.3890561 ],
       [ 2.71828183,  7.3890561 , 20.08553692, 20.08553692],
       [20.08553692, 20.08553692, 20.08553692,  7.3890561 ]])

In [143]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.47712125, 0.30103   ],
       [0.        , 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.47712125, 0.47712125, 0.30103   ]])