In [1]:
import numpy as np

In [2]:
#Sort Search & counting Function

In [3]:
arr = np.array([1,3,5,6,3,6,4,3])

In [4]:
arr

array([1, 3, 5, 6, 3, 6, 4, 3])

In [5]:
np.sort(arr)

array([1, 3, 3, 3, 4, 5, 6, 6])

In [6]:
np.searchsorted(arr,34)

np.int64(8)

In [7]:
arr1 = np.array([0,2,4,3,2,2,2,2,6,5])

In [8]:
np.count_nonzero(arr1)

9

In [9]:
arr

array([1, 3, 5, 6, 3, 6, 4, 3])

In [11]:
np.where(arr>4)

(array([2, 3, 5]),)

In [15]:
np.extract(arr>4,arr)

array([5, 6, 6])

In [16]:
#numpy - byte swapping

In [17]:
arr.byteswap()

array([ 72057594037927936, 216172782113783808, 360287970189639680,
       432345564227567616, 216172782113783808, 432345564227567616,
       288230376151711744, 216172782113783808])

In [18]:
#numpy - copies & views

In [19]:
arr

array([1, 3, 5, 6, 3, 6, 4, 3])

In [20]:
a = np.copy(arr)

In [21]:
a

array([1, 3, 5, 6, 3, 6, 4, 3])

In [22]:
b = arr.view()

In [23]:
b

array([1, 3, 5, 6, 3, 6, 4, 3])

In [24]:
b[0] = 67

In [25]:
b

array([67,  3,  5,  6,  3,  6,  4,  3])

In [26]:
arr

array([67,  3,  5,  6,  3,  6,  4,  3])

In [27]:
#Numpy - matrix Library

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones([2,4])

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
#numpy - linear Algebra

In [34]:
arr1 = np.random.randint([[2,3],[4,5]])

In [37]:
arr2 = np.random.randint([[5,3],[4,5]])

In [38]:
np.dot(arr1,arr2)

array([[5, 5],
       [5, 5]], dtype=int32)